[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Match your Next.js version (you're on 15.5.0)
  NEXT_PRIVATE_TARGET_VERSION = "15.5.0"
  # Make sure Supabase variables are available during build & runtime
  NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}"

[[plugins]]
  package = "@netlify/plugin-nextjs"
