[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Match your Next.js version (you're on 15.5.0)
  NEXT_PRIVATE_TARGET_VERSION = "15.5.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"
